from app.graph.nodes.utils.node_class import Node
from app.graph.nodes.utils.property_metadata import PropertyMetadata

Text = Node(
    table_name="Text",
    pk="id",
    metadata=[
        PropertyMetadata(
            label="id",
            col="H-ID",
            type="INT",
        ),
        PropertyMetadata(
            label="name",
            col="preferred_name",
            type="STRING",
        ),
        PropertyMetadata(
            label="language",
            col="language_COLUMN",
            type="STRING",
        ),
        PropertyMetadata(
            label="form",
            col="literary_form",
            type="STRING",
        ),
        PropertyMetadata(
            label="is_hypothetical",
            type="BOOLEAN",
        ),
        PropertyMetadata(
            label="hypothesis",
            col="claim_freetext",
            type="STRING",
        ),
        PropertyMetadata(
            label="alternative_names",
            type="STRING[]",
        ),
        PropertyMetadata(
            label="is_peripheral",
            col="peripheral",
            type="BOOLEAN",
        ),
        PropertyMetadata(
            label="length",
            type="FLOAT",
        ),
        PropertyMetadata(
            label="length_freetext",
            type="STRING",
        ),
        PropertyMetadata(
            label="verse_type",
            type="STRING",
        ),
        PropertyMetadata(
            label="rhyme_type",
            type="STRING",
        ),
        PropertyMetadata(
            label="stanza_type",
            col="Stanza_type",
            type="STRING",
        ),
        PropertyMetadata(
            label="tradition_status",
            type="STRING",
        ),
        PropertyMetadata(
            label="has_lost_older_version",
            type="BOOLEAN",
        ),
        PropertyMetadata(
            label="lost_older_version_freetext",
            col="ancient_translations_freetext",
            type="STRING",
        ),
        PropertyMetadata(
            label="rewritings_freetext",
            type="STRING",
        ),
        PropertyMetadata(
            label="note",
            type="STRING",
        ),
        PropertyMetadata(
            label="creation_date",
            col="date_of_creation",
            temporal=True,
        ),
        PropertyMetadata(
            label="creation_date_certainty",
            col="date_of_creation_certainty",
            type="STRING",
        ),
        PropertyMetadata(
            label="creation_date_freetext",
            col="date_freetext",
            type="STRING",
        ),
        PropertyMetadata(
            label="described_at_URL",
            type="STRING[]",
        ),
    ],
    table="TextTable",
)
