from app.graph.nodes.utils.node_class import Node
from app.graph.nodes.utils.property_metadata import PropertyMetadata


Witness = Node(
    table_name="Witness",
    pk="id",
    metadata=[
        PropertyMetadata(
            label="id",
            col="H-ID",
            type="INT",
        ),
        PropertyMetadata(
            label="is_unobserved",
            type="BOOLEAN",
        ),
        PropertyMetadata(
            label="hypothesis",
            col="claim_freetext",
            type="STRING",
        ),
        PropertyMetadata(
            label="siglum",
            col="preferred_siglum",
            type="STRING",
        ),
        PropertyMetadata(
            label="alternative_sigla",
            type="STRING[]",
        ),
        PropertyMetadata(
            label="status_witness",
            type="STRING",
        ),
        PropertyMetadata(
            label="status_note",
            col="status_notes",
            type="STRING",
        ),
        PropertyMetadata(
            label="is_excerpt",
            type="BOOLEAN",
        ),
        PropertyMetadata(
            label="creation_date",
            col="date_of_creation",
            temporal=True,
        ),
        PropertyMetadata(
            label="creation_date_certainty",
            col="date_of_creation_certainty",
            type="STRING",
        ),
        PropertyMetadata(
            label="creation_date_freetext",
            col="date_freetext",
            type="STRING",
        ),
        PropertyMetadata(
            label="described_at_URL",
            type="STRING[]",
        ),
    ],
    table="Witness",
)
