from app.graph.nodes.utils.node_class import Node
from app.graph.nodes.utils.property_metadata import PropertyMetadata

Witness = Node(
    node_label="Witness",
    pk="id",
    node_properties=[
        PropertyMetadata(
            property_label="id",
            duckdb_col="H-ID",
            property_type="INT",
        ),
        PropertyMetadata(
            property_label="is_unobserved",
            property_type="BOOLEAN",
        ),
        PropertyMetadata(
            property_label="hypothesis",
            duckdb_col="claim_freetext",
            property_type="STRING",
        ),
        PropertyMetadata(
            property_label="siglum",
            duckdb_col="preferred_siglum",
            property_type="STRING",
        ),
        PropertyMetadata(
            property_label="alternative_sigla",
            property_type="STRING[]",
        ),
        PropertyMetadata(
            property_label="status_witness",
            property_type="STRING",
        ),
        PropertyMetadata(
            property_label="status_note",
            duckdb_col="status_notes",
            property_type="STRING",
        ),
        PropertyMetadata(
            property_label="is_excerpt",
            property_type="BOOLEAN",
        ),
        PropertyMetadata(
            property_label="creation_date",
            duckdb_col="date_of_creation",
            is_temporal=True,
        ),
        PropertyMetadata(
            property_label="creation_date_certainty",
            duckdb_col="date_of_creation_certainty",
            property_type="STRING",
        ),
        PropertyMetadata(
            property_label="creation_date_freetext",
            duckdb_col="date_freetext",
            property_type="STRING",
        ),
        PropertyMetadata(
            property_label="described_at_URL",
            property_type="STRING[]",
        ),
    ],
    duckdb_table="Witness",
)
